[theme]
base = "dark"  #dark theme as a default for every device and every user
primaryColor = "#1a73e8"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#ffffff"
font = "sans serif"

pageTitle = "My Study App"  # Set your desired app name here
favicon = "ğŸ“"  # Optional: You can also set a custom emoji or favicon
