[[pages]]
path = "BEST_PDF_STUDY_APP.py"
name = "SmartExam Creator"
icon = "ğŸ“"

[[pages]]
path = "pages/ğŸ“„ Chat_with_PDF.py"
name = "Chat with PDF"
icon = "ğŸ“„"

[[pages]]
path = "pages/ğŸ–¼ï¸ Chat_with_Images.py"
name = "Chat with Images"
icon = "ğŸ–¼ï¸"

[[pages]]
path = "pages/ğŸ§  Knowledge_Graphs.py"
name = "Summarize & Knowledge Graphs"
icon = "ğŸ§ "

[[pages]]
path = "pages/ğŸ’µ Pricing.py"
name = "Pricing"
icon = "ğŸ’µ"


