[[pages]]
path = "BEST_PDF_STUDY_APP.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/ğŸ“„ Chat_with_PDF.py"
name = "Page 2"
icon = ":books:"
url_path = "my_books" # You can override the default url path for a page
