[[pages]]
path = "BEST_PDF_STUDY_APP.py"
name = "SmartExam Creator"
icon = "ğŸ“"

[[pages]]
path = "pages/ğŸ“„ Chat_with_PDF.py"
name = "Chat with PDF"
icon = "ğŸ“„"

[[pages]]
path = "pages/ğŸ–¼ï¸ Chat_with_Images.py"
name = "Chat with Images"
icon = "ğŸ–¼ï¸"

[[pages]]
path = "pages/1_0_Summaries_no_graphs_Count.py"
name = "Summarize"
icon = "ğŸ§ "


[[pages]]
path = "pages/ğŸ’µ Pricing.py"
name = "Pricing"
icon = "ğŸ’µ"

[[pages]]
path = "pages/2_2_Smartexam_Genrator_bugs_fixed_new_login_paid.py"
name = "Test_new_smartexam"
icon = "ğŸ“"


